services:
  - docker

script:
  - docker build --no-cache -t anicos/tuya-mqtt:"$VERSION" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push anicos/tuya-mqtt:"$VERSION"
