services:
  - docker

script:
  - docker build --no-cache -t tuya-mqtt:"$VERSION" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tuya-mqtt:"$VERSION"
