services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --no-cache -t anicos/tuya-mqtt:$VERSION-linux-amd64 .
  - docker push nicos/tuya-mqtt:$VERSION-linux/arm64
